from datetime import datetime
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('supermarket.csv')
df['Date'] = pd.to_datetime(df['Date'])

def p_m():
    global df
    sns.countplot(x='City', hue='Payment',data=df).set_title("Payment method by city")
    ax = plt.gca()

    # ylim max value to be set
    y_max = df[['City','Payment']].value_counts().max() 
    ax.set_ylim([0, y_max+20])

    # Iterate through the list of axes' patches
    for p in ax.patches:
        ax.text(p.get_x() + p.get_width()/2., p.get_height(), '%d' % int(p.get_height()), 
                fontsize=12, ha='center', va='bottom')
    plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
    plt.show()

def m_s():
    global df
    df['Date'] = pd.to_datetime(df['Date']).dt.date
    df['month_year'] = pd.to_datetime(df['Date']).dt.to_period('M')
    df['month_year'] = df['month_year'].astype('str')
    df = df.sort_values(['month_year','Date'],ascending=True)
    plt.figure(figsize=(12,5))
    sns.lineplot(data=df, x="month_year", y="Total", hue="City",style="City",ci=None).set_title('Net income generated by branch per month.')
    plt.xlabel('Month')
    plt.show()